version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - docker run --rm -v $(pwd):/app -w /app python:3.11 pip install -r requirements.txt -t .

  pre_build:
    commands:
      - echo "Checking PATH..."
      - echo $PATH
      - echo "Listing installed packages..."
      - ls -l

  build:
    commands:
      - echo "Running github-to-lambda..."
      - python lambda_function.py || { echo "github-to-lambda command failed"; exit 1; }
      - echo "Zipping deployment package..."
      - zip -r9 deployment_package.zip . -x "*.git*" -x "*.github*" -x "buildspec.yml" -x "venv/*"

  post_build:
    commands:
      - echo "Updating lambda Function..."
      - aws lambda update-function-code --function-name github-to-lambda --zip-file fileb://deployment_package.zip
      - echo "DONE!!"

artifacts:
  files:
    - deployment_package.zip
