version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - python -m venv venv
      - source venv/bin/activate
      - pip install --upgrade pip
      - pip install wheel
      - pip install -r requirements.txt
  pre_build:
    commands:
      - echo "Checking PATH..."
      - echo $PATH
      - echo "Listing installed packages..."
      - source venv/bin/activate
      - pip list
  build:
    commands:
      - echo "Running github-to-lambda..."
      - source venv/bin/activate
      - python lambda_function.py || { echo "github-to-lambda command failed"; exit 1; }
      - echo "Zipping deployment package..."
      - deactivate
      - zip -r9 deployment_package.zip . -x "*.git*" -x "*.github*" -x "buildspec.yml" -x "venv/*"
  post_build:
    commands:
      - echo "Updating lambda Function..."
      - aws lambda update-function-code --function-name github-to-lambda --zip-file fileb://deployment_package.zip
      - echo "DONE!!"
artifacts:
  files:
    - deployment_package.zip
